recipe: default.v1
language: id
pipeline:
- name: SingleStepLLMCommandGenerator
  llm:
    provider: openai
    model: gpt-4o-mini


policies:
- name: FlowPolicy
#  - name: EnterpriseSearchPolicy
#  - name: RulePolicy

assistant_id: 20241021-082830-neat-bike
