recipe: default.v1
language: id
pipeline:
- name: NLUCommandAdapter
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 100
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100

- name: SingleStepLLMCommandGenerator
  llm:
    provider: openai
    model: gpt-4-0613


policies:
- name: FlowPolicy
#  - name: EnterpriseSearchPolicy
# - name: RulePolicy

- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 200
- name: RulePolicy

assistant_id: 20241025-014428-ascent-brass
