recipe: default.v1
language: id
pipeline:
- name: SingleStepLLMCommandGenerator
  llm:
    provider: openai
    model: gpt-4-0613


policies:
- name: FlowPolicy
#  - name: EnterpriseSearchPolicy
#  - name: RulePolicy
assistant_id: 20241022-080459-commutative-sort
